### ISSUE TITLE
I can't use the form exit

### ISSUE THREAD

**Issue by Yamakuni** [pytesNET/tail.select#10]
Hey everyone,

I'm sorry, but if you have time, I need help for something.
I try to create a dynamic form, but when I add 'class="select"' at 'select' tag, the form no longer works.

I created 2 forms in CodePen for show you : 
- With 'class="select"' : https://codepen.io/anon/pen/eQmNKB
- Whithout  : https://codepen.io/anon/pen/RqNPjY

Thanks a lot for your help.

**Comment by SamBrishes** [comment]
Hello,

thanks for the issue. First of all: You bind your function to the "onclick" event, which isn't wrong but the "onchange" event would be a better choice. 

But this wouldn't work either, because my Script currently doesn't trigger any event on the source select element. So you need to bind your function to my script, instead to the source select element. The following would theoretically work...

```javascript
tail.select(".select").on("change", function(){
    var paystemp = document.getElementById("pays").value;
    if(paystemp == "espagne"){
        document.getElementById("ville_d_espagne").style.display = "block";
    } else {
        document.getElementById("ville_d_espagne").style.display = "none";
    }
});
```

... but now you have the Problem that the second Select field isn't a `tail.select` instance. The current version currently doesn't check if the select field is visible to the user or not.

The real Solution
-----------------
To make it short: To fix my buggy Script according to your issue try out this [CodePen](https://codepen.io/anon/pen/WYbojq). My Fix will turn both of your select fields into a `tail.select` instance and "copies" the class Names of the source select fields (The second select field has the class Name "hidden"). 

Next: Your function has been moved the the internal event listener `.on("change")`, which changes the `style.display` proeprty directly on the respective `tail.select` instance of the second select field.

```javascript
var selects = tail.select(".select", {classNames: true});

// Bind Change Event on First Select Field
selects[0].on("change", function(){
    var source = document.getElementById("pays"),
        espagne = document.querySelector("#ville_d_espagne");

    if(source.value == "espagne"){
        tail.select(espagne).select.style.display = "block";
    } else {
        tail.select(espagne).select.style.display = "none";
    }
});
```

I hope this works for you.

Sincerely,
Sam.

<br /><br /><br /><br />
###### Internal Dev Notice (0.4.3)
- [ ] Trigger Source Select Events
- [ ] Check Visibility of the Source Select Field (Copy Style Attribute)
- [ ] Unify the reutrn value of `tail.select` (Single vs. Multiple)

**Comment by Yamakuni** [comment]
Hey SamBrishes!
Thank you very much for your answer.
I don't understand everything, but it's normal, my level of JS is really low.
I think I'll be waiting 5 milestone (with Trigger Source Select Events). :-) 

But your support helps me a lot, and gives me a lot of ideas.
Thank you, and sorry for the delay in my answer....

**Comment by SamBrishes** [comment]
Hellow,

Version 0.5.0 / 0.5.2 is out now and triggers now also the "change" and "input" events on the source select field. You can find a small example on jsFiddle:

https://jsfiddle.net/SamBrishes/fz4qxu9c/13/

No Problem, and thank you too!

Sincerely,
Sam.

PS.: I can really recommend [w3schools.com](https://www.w3schools.com/js/default.asp) and [Mozillas MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript) for learning JavaScript.
