### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by arabine** [pytesNET/tail.select#11]
Here is a first french translation, I have a doubt for placeholderMulti and search, can you provide a real example of this test so that I can understand precisely the context.

`all: "Tous",
none: "Aucun",
actionAll: "Sélectionner tout,
actionNone: "Sélectionner aucun",
empty: "Aucune option disponible",
emptySearch: "Aucune option trouvée",
limit: "Aucune autre option sélectionnable",
placeholder: "Choisissez une option ...",
placeholderMulti: "Choisissez jusqu'à : limit option(s) ...",
search: "Rechercher ..."
`

Edit: sorry I just read the process to submit a PR for translation. By the way, the translation should be per select instance, since we can have several instances in one page...

**Comment by SamBrishes** [comment]
Hello,

Thanks for translating my script. I'm currently not on my Computer but I tried to write a small example on my smartphone:

https://codepen.io/sambrishes/pen/qQNLpp

- `placeholderMulti` is used on multiple select fields, which are limit to a number of options. ':limit' should not be translated because this part of the string gets replaced by the respective number of selectable options.
- `search` ist the placeholder string for the input field within the dropdown menu. 

And thanks for the suggestion. The current version sets the respective language strings for the complete environment. I will change this in the next update.

Sincerely,
Sam.

**Comment by arabine** [comment]
Ok understood, I changed a bit some translations. 

In the wiki, cbLoopItem:         undefined   // NEW IN 0.4.0  <<== missing a coma here

Can you also propose a flat (modernize) CSS style (with bigger font/selectable area) so that it can be integrated seamlessly in a Bootstrap-like CSS?

**Comment by SamBrishes** [comment]
Hello,

I'm really sorry for the long wait. And Thanks, I already implemented the translations and a new "locale" settings into the new update.

I'm not really into Bootstrap right now, do you mean something like this: [codepen.io](https://codepen.io/sambrishes/pen/rQwpaJ?editors=1100). This is just a basic design, which I found on [getbootstrap.com](https://getbootstrap.com/docs/4.1/components/dropdowns/).

Thanks.

Sincerely,
Sam.

**Comment by arabine** [comment]
Yes, something like that, without any dependency on bootstrap ; It could be then easily integrated on many websites using flat design without any modifications, or at least the color.

**Comment by arabine** [comment]
yep, well done!

This field is disabled ==> Ce champs est désactivé

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your help, version 0.5.0 has been released now. Issue closed.

Sincerely,
Sam.
