### ISSUE TITLE
Allow optgroup collapse/expand

### ISSUE THREAD

**Issue by wolffe** [pytesNET/tail.select#111]
Allow `<optgroup>` collapse/expand similar to Select2's one - https://stackoverflow.com/a/52157352/2987930

**Comment by SamBrishes** [comment]
Hellow,

thanks for your request.

This feature has already been requested in [#36](https://github.com/pytesNET/tail.select/issues/36) and will be released with 0.6.0 or 1.0.0 as additional plugin.

Sincerely,
Sam.

**Comment by wolffe** [comment]
Thanks @SamBrishes 

Any timeline for this version? Or a roadmap?

**Comment by SamBrishes** [comment]
No sorry, I don't have any timeline or roadmap.

I hope the new version gets released on end of January, since the most things are done. I'm still testing and fixing the new environment, building up the new documentation and demonstration website and writing the 5 core plugins and 2 new core themes.

**Comment by wolffe** [comment]
That's a lot :)

Okay, looking forward to see the new version.
