### ISSUE TITLE
Number of options selected

### ISSUE THREAD

**Issue by Chris-Beckett** [pytesNET/tail.select#117]
Hello there, 

currently when you have all options selected and you've got search enabled. You can search the results to filter to the option you would like to deselect which is great. However when you click 'unselect all' it deselects all the ones which you've filtered out, this works great. 

When you keep clicking the 'unselect all' the number of options selected label keeps decreasing. This will result in the label stating '0' while you have multiple options selected which you didn't search on.

Please find the attach screenshots:

![Tail select 1](https://user-images.githubusercontent.com/49186278/70539283-6218fc80-1b5b-11ea-9b13-5dfd163cebaf.PNG)

![tail select 2](https://user-images.githubusercontent.com/49186278/70539287-62b19300-1b5b-11ea-89cd-d349bb8c9433.PNG)

![Tail select 3](https://user-images.githubusercontent.com/49186278/70539284-6218fc80-1b5b-11ea-8e7b-340a54a5da83.PNG)

![tail select 4](https://user-images.githubusercontent.com/49186278/70539286-6218fc80-1b5b-11ea-8e1c-99c85f336b48.PNG)

Is there any way to override any of the unselect functionality to detect if it's in searching state and to re update the label to the correct count instead of keep decreasing when clicking unselect all?

**Comment by SamBrishes** [comment]
Hellow,

thanks for showing. This is a terrible bug, since it's not just the counter goes down, also the internal selection array gets cleared by the amount of items of the search (so other selected options gets internally unselected). This behaviour gets removed in 0.6.0, because this version doesn't store the options anymore and only uses the source `<select>` container.

I'll try to add a hotfix for this in the upcoming 0.5.16 version.

Sincerely,
Sam.

**Comment by Chris-Beckett** [comment]
Hello Sam,

Thank you for getting back to my issue. 

When will the release be for this problem to be resolved?

Chris

**Comment by SamBrishes** [comment]
Fixed in the upcoming release 0.6.0
