### ISSUE TITLE
Ignores disabled attribute

### ISSUE THREAD

**Issue by ashucg** [pytesNET/tail.select#12]
Please see: https://jsfiddle.net/sd54puek/

- Don't you think that original select element should be disabled after tail.select() is called? FormData API reads both the fields, you can try that by removing `disabled` attribute for `.tail-select` in the fiddle and click on **Done** button, `counter` will be incremented by 2.
- If select element is disabled, it should not be possible to select values in tail.select instance.
- Also, there should be a function to switch enable/disable states for entire dropdown.

**Comment by SamBrishes** [comment]
Hellow

oops I'm sorry, I thought I had already answered here.

To your 1st point: This is a bug according to the csvInput field, which gets rendered even if the option is disabled. The option also reserves the `name` attribute on the source select field (even if used correctly), whereby the FormData API counts both fields. Both bugs gets fixed in 0.5.0!

2nd Point: Thats correct of course! The new version contains a "disabled" option, which gets overwritten by the respective attribute of the source field. This option will disable all interactions with the single options (and the dropdown field).

3th Point: Version 0.5.0 contains a `.enable()` and `.disable()` public methods, which are just aliases for the `disabled` option, descriped above. The new methods are already descriped [on the Wiki](https://github.com/pytesNET/tail.select/wiki/Public-Methods).

Thanks for reporting and I'm really sorry for the long wait!

Sincerely
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your help, version 0.5.0 has been released now. Issue closed.

Sincerely,
Sam.

**Comment by ashucg** [comment]
Thanks for the update and adding the feature, I would suggest you to update Wiki to include:
- You should use `.disable()` if you want options to be visible even in disabled state
- If the select element is disabled using `disabled` attribute - you must enable it using `.config('disabled', false)` instead of `.enable()`
both of these points are based on [this fiddle](https://jsfiddle.net/sd54puek/2/)

Also, `enable()`, `disable()`, `config('disabled', true|false)` are not updating the actual DOM element - which affects FormData API - see [this fiddle](https://jsfiddle.net/sd54puek/3/)

**Comment by SamBrishes** [comment]
Update has been released and fixes this issue. [jsFiddle](https://jsfiddle.net/SamBrishes/kub7wshq/3/)

Sincerely,
Sam.

**Comment by ashucg** [comment]
Thanks for the fix - it is working as you have mentioned here:

> ### .enable()
> 
> Enables the `tail.select` instance as well as the source select field. (FormData API)
> ### .disable()
> 
> Disables the `tail.select` instance as well as the source select field. (FormData API)
> ### .config("disabled", true)
> 
> Just "disables" the `tail.select` instance without touching the source select field.
> ### .config("disabled", false)
> 
> Just "enables" the `tail.select` instance without touching the source select field.
