### ISSUE TITLE
Translation: {fa_IR}

### ISSUE THREAD

**Issue by abdulhalim** [pytesNET/tail.select#129]
### All
-   "همه"
### None
-   "هیچکدام"
### Select All
-   "انتخاب همه"
### Unselect All
-   "انتخاب هیچکدام"
### No Options available
-   "انتخابی موجود نیست"
### No Options found
-   "انتخابی یافت نشد"
### You can't select more Options
-   "نمیتوانید گزینه‌های بیشتری داشته باشید"
### Select an Option...
-   "یک گزینه ای را انتخاب کنید"
### Select up to :limit Options...
-   "حداکثر انتخاب تا: گزینه‌ها را محدود کنید ..."
### Type in to search...
-   "برای جستجو تایپ کنید..."
### This Field is disabled
-   "کادر غیرفعال است"

**Comment by SamBrishes** [comment]
Hellow,

thanks for your translation :D 

We don't update the 0.5.x release path anymore, so it will be published with the new 0.6.0 version. The problem is, that the new version contains a few changes on the respective strings. You can find the new locale template file on the [0.6.0-dev branch](https://github.com/pytesNET/tail.select/blob/0.6.0-dev/src/locales/_locale_.json) or below this comment.

So could you please re-check if the translation is correct and valid:

[fa_IR.json on branch:0.6.0-dev](https://github.com/pytesNET/tail.select/blob/0.6.0-dev/src/locales/fa_IR.json)

Would be really awesome. Thanks!

----

The new strings:  
```
"buttonAll":        "All",
"buttonNone":       "None",
"disabled":         "This field is disabled",
"empty":            "No options available",
"emptySearch":      "No options found",
"multiple":         "Choose one or more options...",
"multipleCount":    "Choose up to [1] options...",
"multipleLimit":    "No more options selectable...",
"multipleList":     "[0] options selected",
"search":           "Tap to search...",
"single":           "Choose an option..."
```

- `[0]` is the amount of already selected options
- `[1]` is the number of options the user can still select

Both (`[0]` and `[1]`) must remain as they get replaced with the values.

-------

Sincerely,
Sam.

**Comment by abdulhalim** [comment]
Yes, That's All right

**Comment by SamBrishes** [comment]
Thanks, will be a part of 0.6.0
