### ISSUE TITLE
Saving the value option on the server

### ISSUE THREAD

**Issue by makspoll** [pytesNET/tail.select#135]
tail.on("change", function(opt, state) {

//execute a server request ajax

if(ok) {
   this.options.handle("select", opt.key, "#", true);
}
else {
  return false OR this.options.handle("unselect", opt.key, "#", true);
}

});

can i manage the add operation in "on.change" ?

**Comment by SamBrishes** [comment]
Hellow,

thanks for your question.

First of all: You don't need to select the option, if the server returns okay, because the option is already selected. You just need to unselect it if the server returns false.

And yes you can add an option within the `change` event / callback function. I created [an example on jsfiddle](https://jsfiddle.net/yf1rhp3o/1/). The linked example uses an "pseudo-ajax" function for the demonstration. This pseudo function will return true and add another option if you select `Option A`, and false if you select `Option B` or `Option C` (which will also unselect them).

The used code:
```javascript
let select = tail.select("select");
select.on("change", function(option, state) {
    if(state  !== "select") {
        return;
    }
    let self = this;

    // Pseudo Ajax Function
    let ajax = (function(opt, func) {
        setTimeout(function() {
            if(opt.value === "Option A") {
                func.call(self, opt, true);
            } else {
                func.call(self, opt, false);
            }
        }, 150);
    });

    // Handle Request
    ajax(option, function(opt, status) {
        if(status === false) {
            this.options.handle("unselect", opt.key, "#", true);
            return;
        }

        this.options.add("option-d", "Option D", "#", false, false, null, true);
    });
});
```
Sincerely,
Sam.

**Comment by makspoll** [comment]
Thanks for the quick response!

  I just thought that I could stop the execution of "change" and operate on adding or removing an option manually in the context of "change"

I implemented the functionality as you described, thanks for your quick reply!
