### ISSUE TITLE
Single select not applying placeholder value. Multiselect option works.

### ISSUE THREAD

**Issue by danhumaan** [pytesNET/tail.select#26]
I'm running an implementation with up to 6 selects in an individual form. 1 of those is a multiple select, and the others are only single, however the placeholder attribute is not being applied as expected.

Whether it's `placeholder` or `data-placeholder` makes no difference. The placeholder for single selects does not get applied. where it does for Multiple.

I'm using jQuery elsewhere so my implementation looks like this:
```html
<select class="custom-select" data-multiple="true" data-placeholder="Multi select placeholder">
    <option>Multi option 1</option>
    <option>Multi option 2</option>
    <option>Multi option 3</option>
</select>
<select class="custom-select" data-placeholder="Single select placeholder">
    <option>Single select option 1</option>
    <option>Single select option 2</option>
</select>
```
```js
$('.custom-select').each(function() {
    var opts = {
        classNames: 'swps-custom-select'
    };
    var self = $(this);
    if ( self.attr('data-multiple') ) {
        opts['multiple'] = true;
        opts['multiSelectAll'] = true;
    }
    if ( self.attr('data-placeholder') ) {
        opts['placeholder'] = self.attr('data-placeholder');
    }

    tail.select(self[0], opts);
});
```
No demo url is available for this implementation.

The same issue still exists even when initialised uniquely, and not in the jquery .each function, like so.
```js
tail.select(document.querySelector('.standalone'),{
    placeholder: "Placeholder Text"
});
```
Any suggestions on fix?

**Comment by SamBrishes** [comment]
Hellow,

a single select field need to be `deselect`able to show the placeholder as shown on [this jsFiddle](https://jsfiddle.net/qxL0adzv/).

The respective code:
```javascript
$('.custom-select').each(function() {
    var opts = {
        classNames: 'swps-custom-select'
    };
    var self = $(this);
    if ( self.attr('data-multiple') ) {
        opts['multiple'] = true;
        opts['multiSelectAll'] = true;
    } else {
        opts['deselect'] = true;
    }
    if ( self.attr('data-placeholder') ) {
        opts['placeholder'] = self.attr('data-placeholder');
    }

    tail.select(self[0], opts);
});
```

### Background
That's happening, because the user itself isn't able to deselect a single select field, the user agent will always pre-select the first not disabled option (as described on [W3Cs HTML Standard](https://www.w3.org/TR/html50/forms.html#the-select-element)). Only the developer has the possibility to change this, by setting the `selectedIndex` to `-1`. 

The tail.select script doesn't support to set a custom `selectedIndex`, but the `deselect` option to achieve that (and allow the user also to deselect an option).

Sincerely,
Sam.

**Comment by danhumaan** [comment]
Awesome, thanks for the prompt reply @SamBrishes - that solves the problem and makes perfect sense. I've worked in the deselect option and it's now behaving as expected.

Cheers!
