### ISSUE TITLE
Search. Russian linguistic magic: "е" and "ё"

### ISSUE THREAD

**Issue by tizis** [pytesNET/tail.select#42]
In the Russian alphabet there are two letters that are similar in spelling and sound: "е" and "ё".
In the modern world, when writing "ё" it is often replaced with "е", of course, with the exception of language textbooks, perhaps, documents and so on.

For this reason, the search is currently not working correctly. I can type "актер" meaning "актёр" but get nothing.

It would be cool if the letter "ё" were replaced by "е" when searching

Proof of linguistic magic:
![image](https://user-images.githubusercontent.com/16865573/54939337-8a6fb500-4f52-11e9-9273-7d5c610f9789.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your request. 

The new Version (0.5.9) contains a new experimental option called **`linguisticRules`**, which handles such similar letters. The value of this new option MUST be a `key: value` based object (`{ "е": "ё" }`, for example). Basically, it just turns the letters within the search query into a regular expression before the search is performed. So in your example `актер` would be `акт(е|ё)р` (works also with `актёр`, of course).

## Default Value
You don't need to do or configure anything, because `{ "е": "ё" }` is currently the default value of this new option. So just update to the new version :D. 

Thanks.

Sincerely,
Sam.
