### ISSUE TITLE
Where is the focus on tab?

### ISSUE THREAD

**Issue by spolloz** [pytesNET/tail.select#47]
Best practice is focusing on form elements. And we all know that.

**Comment by danhumaan** [comment]
Second this - the only thing stopping me from using this right now is it's lack of keyboard support.

**Comment by SamBrishes** [comment]
Hellow,

thanks for your request. I added support for tabbing (`tabindex`) as well as for the `space` key (to open a closed selection field). The support for Enter (Return) to select an option and the support to walk through the options using the arrow keys are already available.

Please download try the [updated master branch](https://github.com/pytesNET/tail.select/zipball/master).

Thanks.

Sincerely,
Sam.

**Comment by danhumaan** [comment]
This is a great start, thank you. Looking at the demo page (https://github.pytes.net/tail.select/) I can already see some of it in action.

The main thing i've noticed is that when using the keyboard, the `selected` class that's intended to be implied, is not added with a space in front so the item in the list has a class of `dropdown-optionselected`

Because of that it creates another interaction bug where the arrow keys skip over those items when moving up and down the list.

**Comment by SamBrishes** [comment]
Hellow,

This bug should now be fixed too. 

Thanks, I didn't noticed that during testing. :D 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

the tabindex / Space key support has been pushed into the new release 0.5.11. Thanks for your suggestions, if you still have a missing key, which need to be attached, re-open this issue or create a new one! Thanks :D

Sincerely,
Sam.
