### ISSUE TITLE
Minimal browsers version supported

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#56]
What's the current minimal requirement for majors browsers?
Per example, `elem.scrollBy()`'s support started (without flags) with version 61 of chrome.

It would be nice to write these info in the README.md.

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue and also for mention the `.scrollBy()` function. I guess I didn't checked that as I wrote this code, because `officially` I want to support all major browsers (Firefox, Chrome, Opera, Edge, Safari) at least in the latest version and IE 10+ (as mentioned in the README). So the `.scrollBy()` function must get replaced to achieve this.

## Back to your issue
I don't want to offer an explicit supported browser version (except on IE), because it's kind of impossible to get a specific version (in a support case), at least for Chrome and Edge. The second problem is that Firefox, Chrome and Edge have such a fast update cycle, that it gets really hard to give an exact version number (even just the major version number).

I could pass some "theoretical" numbers (calculated with caniuse.com and MDN), which would be - of course - as low as possible to impress, like many other projects does (and [as I once did it too](https://github.com/pytesNET/tail.select/tree/cac41b7e848711a796248e2e5bb01314a21cb7a7#compatibility)). But I decided to go with this line

`Compatible with all modern browsers (including IE 10+)`

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
