### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by elPesecillo** [pytesNET/tail.select#8]
Hello,

I am doing some test to the component and I found an issue when I tried to use the search option, looks like the search option is not filtering the options as one might expect:

![image](https://user-images.githubusercontent.com/41170549/47042391-c5beba00-d150-11e8-87c6-c550afb1a139.png)

when I type the "val" text only the last option is shown, but what I assume is that all the options that match the "val" text should appear.

those are the options that I used while did my test:
![image](https://user-images.githubusercontent.com/41170549/47042563-32d24f80-d151-11e8-91ab-a0dbfe0d50b6.png)

**Comment by SamBrishes** [comment]
Hello,

Thanks for your report!

that is strange and shouldn't happen. But first of all: You don't need `deselect` when you are using `multiple` select fields, because multiple select fields are `deselect`-able per default while single select ones has an "pre-defined" option.

Back to this problem: I couldn't re-create your issue, [my demo fiddle](https://jsfiddle.net/7nv0yuz9/1/) works at least in the latest Firefox and Chrome browsers and as shown there I tried  `<option>[value]</option>` as well as `<option value="[value]">[value]</option>` element structures. Does your HTML structure looks different? If yes, it would be really helpful if you could post this too.

Thanks.

Sincerely,
Sam.

**Comment by elPesecillo** [comment]
Hello, thanks for the rapid response, I replicate the issue in this fiddle [https://jsfiddle.net/ElPesecillo/sdf2agmw/](url), looks like the issue only occurs when the html is not well tidy (I am generating the html dinamically).

**Comment by SamBrishes** [comment]
Hello,

this issue is fixed, the new RegExp Part isn't greedy anymore and fetchs all option elements, even if there are in a single line.

Sincerely,
Sam.
