### ISSUE TITLE
IE9 to IE11 SCRIPT438: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by twizzlerz04** [pytesNET/tail.select#90]
Object Assign doesn't support on IE9 to IE11
`
function clone(obj, rep){
     return Object.assign({}, obj, rep) || {};
}
`

I tried applying Object Spread but it needs identifier and I don't know how to apply it.
`
function clone(obj, rep){
     return { ...obj, ...rep } || {};
}
`

To be honest, I don't know Object assign and Spread. Just tried this solution.
Can someone help me please?

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue. Which version of the **tail.select** do you use? I'm asking, because the `Object.assign` issue has been fixed with Version 0.5.13 after it occurred in 0.5.12. I also tested the current version on IE11, and it works, since it uses a Fallback when `Object.assign` isn't available.

Oh and btw... I'm not supporting IE9 anymore. This support has been dropped in 0.5.12.

Sincerely,
Sam.

**Comment by twizzlerz04** [comment]
Updating the version fix the issue. Thank you.

**Comment by SamBrishes** [comment]
Perfect, closing here :D
