### ISSUE TITLE
HTMLOptionElement as parameter

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#94]
I think that you could handle HTMLOptionElement as parameter for all methods that take key/group parameter.
Since (as I understand) you only rely on the source `select`, allowing to "play" with source's `option`s seems natural.

You can even generalize it, self-calling those functions with the result of `get(key, group)` that would returns an `option`.

PS: Can you open a new issue with incoming interface changes? (Name and parameters of functions, list of function).
I would appreciate discussing it and maybe helping enhancing at this early stage.

It's not a big deal if some function's name changes from the current beta. Once the definitive interface of the V1 will be defined, we could begin to implements new function names and keep old names as aliases, then displaying displaying warning about their deprecation.

Sincerely.

**Comment by SamBrishes** [comment]
Hellow,

sorry, this issue somehow sneaked past me.

That's the way I want to handle `.get()`. You can either pass a pair of `value, group` values or and `<option>` element and it always returns a loopable object such as an Array, NodeList or HTMLCollection. 

And each available method pass the first parameter to `.get()` so the user / developer can decide, if he selects the `<option>` element by his own or using a `[value, group]` argument. That's what I  [meant here](https://github.com/pytesNET/tail.select/issues/89#issuecomment-516267786).

-----

Yes, when I'm finish designing the new methods structure, I'll post it here. Thanks for your help :D 

It's maybe a bad decision, but I don't want to make v1.0.0 backward compatible with the beta version, because this would contain MANY lines of code to figure out how the old methods has been called and pass / convert them to the new ones. 

I want to keep the source files as small as possible (to fight against all jQuery-dependent alternatives), and want to remove the "old deprecated" stuff directly instead of "poison" the code over several version jumps after it gets deleted.

Sincerely,
Sam.

**Comment by Calak** [comment]
I don't think that not being compatible with earlier versions is a bad decision, especially for a V1.0.0.

So, maybe we should force users to pass a single argument as either a real pair ( `{value: XXX, group: YYY}` ) either an `HTMLOptionElement` (or a collection).

And play with typescript features

Maybe something like:

    namespace tailSelect {
        export interface OptionPair {
            value: string|number;
            group?: string|null;
        }
        export type Option = tailSelect.OptionPair | HTMLOptionElement;

        export interface OptionFilter {
            selected?: boolean|null;
            disabled?: boolean|null;
            hidden?: boolean|null;
        }
    }
    //...
    class tailSelect {
    source: HTMLSelectElement;
    constructor(source: HTMLSelectElement) {
        //...

    }

    //...

    get(option: tailSelect.Option, filter: tailSelect.OptionFilter = {}) : any[] {
        let selector = '';
        if (typeof filter.selected === "boolean") selector += (filter.selected) ? ":checked"  : ":not(:checked)"
        if (typeof filter.disabled === "boolean") selector += (filter.disabled) ? ":disabled" : ":not(:disabled)"
        if (typeof filter.hidden === "boolean")   selector += (filter.hidden)   ? "[hidden]"  : ":not([hidden])"
 
        //...   
   
For the return type, it would be better not to have as many types as `array`, `NodeList` or `HTMLCollection`, `HTMLOptionCollection` or other, but one and only one.

**Comment by SamBrishes** [comment]
This will be featured in the upcoming release 0.6.0
